springdoc:
  api-docs:
    path: /service-admin-panel/v3/api-docs  # path modified where swagger-ui works
  swagger-ui:
    path: /service-admin-panel/swagger-ui.html
#http://localhost:9090/service-auth/swagger-ui/index.html --> by default url
